ALTER TABLE packages ADD COLUMN IF NOT EXISTS category_slug TEXT NOT NULL DEFAULT 'custom';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS category_name TEXT NOT NULL DEFAULT 'Custom Packages';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS display_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS marketing_consent BOOLEAN NOT NULL DEFAULT false;
